// Arabic Darja (Algerian Arabic) localization strings
// All UI text in proper Algerian Arabic

export const AR = {
    // Common
    yes: "نعم",
    no: "لا",
    loading: "جاري التحميل...",
    saving: "جاري الحفظ...",
    error: "خطأ",
    success: "تم بنجاح",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    confirm: "تأكيد",
    cancel: "إلغاء",
    close: "إغلاق",
    delete: "حذف",
    edit: "تعديل",
    save: "حفظ",
    search: "بحث",
    filter: "تصفية",
    logout: "تسجيل خروج",
    login: "تسجيل دخول",

    // Navigation
    home: "الرئيسية",
    products: "المنتجات",
    cart: "السلة",
    myOrders: "طلباتي",
    profile: "الملف الشخصي",
    admin: "إدارة",
    adminDashboard: "لوحة التحكم",

    // Home Page
    welcome: "أهلا بك في هو بارفيوم",
    welcomeSubtitle: "أفضل العطور والروائح الفاخرة",
    exploreProducts: "اكتشف المنتجات",
    featuredProducts: "المنتجات المميزة",
    whyChooseUs: "لماذا تختارنا",
    howItWorks: "كيفية التطبيق",
    newsletter: "النشرة البريدية",
    subscribeEmail: "اشترك في نشرتنا البريدية",
    email: "البريد الإلكتروني",

    // Features
    qualityProducts: "منتجات أصلية",
    fastDelivery: "توصيل سريع",
    securePayment: "دفع آمن",
    customerSupport: "دعم العملاء",
    luxuryFragrance: "روائح فاخرة",
    authenticity: "الأصالة",
    premiumQuality: "جودة عالية",
    algeriAn: "جزائرية",

    // Products
    price: "السعر",
    stock: "المخزون",
    quantity: "الكمية",
    addToCart: "أضف للسلة",
    outOfStock: "غير متوفر",
    category: "الفئة",
    description: "الوصف",
    inStock: "متوفر",
    details: "التفاصيل",
    reviews: "التقييمات",

    // Product Categories
    perfumes: "عطور",
    womenPerfumes: "عطور نسائية",
    menPerfumes: "عطور رجالية",
    luxuryPerfumes: "عطور فاخرة",
    scents: "الروائح",
    candles: "شموع عطرية",
    scentedCandles: "شموع معطرة",
    incense: "بخور",
    luxuryCandles: "شموع فاخرة",
    waxMelts: "شموع الشمع المذاب",
    candleSet: "مجموعة شموع",
    candleBundle: "مجموعة شموع مرتبطة",
    fragranceCandle: "شمعة معطرة",
    aromatic: "عطري",
    burnTime: "وقت الاحتراق",
    hours: "ساعات",

    // Cart
    cartEmpty: "السلة فارغة",
    cartTotal: "الإجمالي",
    checkout: "إتمام الشراء",
    continueShopping: "متابعة التسوق",
    removeFromCart: "إزالة من السلة",
    updateCart: "تحديث السلة",
    subTotal: "المجموع الجزئي",
    shippingCost: "تكلفة التوصيل",
    taxes: "الضرائب",
    total: "المجموع",

    // Authentication
    register: "إنشاء حساب",
    registerNow: "سجل الآن",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    name: "الاسم",
    password: "كلمة المرور",
    passwordConfirm: "تأكيد كلمة المرور",
    phone: "الهاتف",
    passwordsMustMatch: "كلمات السر يجب أن تتطابق",
    emailAlreadyExists: "البريد الإلكتروني موجود بالفعل",
    invalidEmail: "البريد الإلكتروني غير صحيح",
    passwordTooShort: "كلمة المرور قصيرة جداً",
    registerSuccess: "تم التسجيل بنجاح!",
    loginSuccess: "تم التسجيل الدخول بنجاح!",
    forgotPassword: "هل نسيت كلمة المرور؟",
    rememberMe: "تذكرني",
    signIn: "دخول",
    signUp: "تسجيل",
    verifyEmail: "تحقق من بريدك الإلكتروني",
    verificationCode: "رمز التحقق",
    resendCode: "إعادة إرسال الرمز",
    codeExpired: "انتهت صلاحية الرمز",

    // Orders
    orders: "الطلبات",
    myOrders: "طلباتي",
    orderNumber: "رقم الطلب",
    orderStatus: "حالة الطلب",
    orderDate: "تاريخ الطلب",
    orderTotal: "إجمالي الطلب",
    orderDetails: "تفاصيل الطلب",
    trackOrder: "تتبع الطلب",
    placeOrder: "إنشاء طلب",
    orderPlaced: "تم إنشاء الطلب بنجاح",
    noOrders: "لا توجد طلبات",
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    shipped: "تم الشحن",
    delivered: "تم التسليم",
    cancelled: "ملغى",

    // Order Status (Arabic Darja)
    requested: "جديد",
    under_discussion: "قيد المناقشة",
    payed: "تمّ الدفع",
    delivering: "جاري التوصيل",
    delivered_successfully: "توصّل بنجاح",

    // User Profile
    userProfile: "الملف الشخصي",
    editProfile: "تعديل الملف الشخصي",
    saveChanges: "حفظ التغييرات",
    profileUpdated: "تم تحديث الملف الشخصي",
    telegramUsername: "اسم Telegram",
    linkTelegram: "ربط Telegram",
    telegramLinked: "تم الربط",
    notLinked: "لم يتم الربط",
    accountSettings: "إعدادات الحساب",
    changePassword: "تغيير كلمة المرور",
    newPassword: "كلمة المرور الجديدة",
    currentPassword: "كلمة المرور الحالية",

    // Admin
    adminPanel: "لوحة إدارة",
    dashboard: "لوحة التحكم",
    statistics: "الإحصائيات",
    totalOrders: "إجمالي الطلبات",
    todayOrders: "طلبات اليوم",
    newOrders: "طلبات جديدة",
    completedOrders: "طلبات مكتملة",
    totalUsers: "إجمالي المستخدمين",
    totalRevenue: "الإيرادات الإجمالية",
    recentOrders: "الطلبات الأخيرة",
    manageOrders: "إدارة الطلبات",
    manageProducts: "إدارة المنتجات",
    addProduct: "إضافة منتج",
    editProduct: "تعديل المنتج",
    deleteProduct: "حذف المنتج",
    productName: "اسم المنتج",
    productAdded: "تم إضافة المنتج",
    productUpdated: "تم تحديث المنتج",
    productDeleted: "تم حذف المنتج",
    confirmDelete: "هل أنت متأكد من الحذف؟",
    updateStatus: "تحديث الحالة",
    statusUpdated: "تم تحديث الحالة",
    adminLogout: "خروج المدير",
    adminLogin: "دخول المدير",
    adminPassword: "كلمة مرور المدير",
    adminEmail: "بريد المدير",

    // Messages
    successMessage: "تم بنجاح",
    errorMessage: "حدث خطأ",
    warningMessage: "تحذير",
    infoMessage: "معلومة",
    confirmMessage: "هل أنت متأكد؟",
    tryAgain: "حاول مجدداً",
    contactSupport: "تواصل مع الدعم",
    noInternet: "لا توجد اتصال بالإنترنت",
    tryLater: "حاول لاحقاً",

    // Validation
    requiredField: "هذا الحقل مطلوب",
    invalidInput: "إدخال غير صحيح",
    fieldTooShort: "الحقل قصير جداً",
    fieldTooLong: "الحقل طويل جداً",

    // Telegram
    linkTelegramButton: "ربط Telegram",
    unlinkTelegram: "فصل Telegram",
    telegramNotifications: "إشعارات Telegram",
    enableNotifications: "تفعيل الإشعارات",
    disableNotifications: "تعطيل الإشعارات",

    // Notifications
    orderConfirmed: "تم تأكيد طلبك",
    orderShipped: "تم شحن طلبك",
    orderDelivered: "تم تسليم طلبك",
    paymentReceived: "تم استقبال الدفع",
    newMessage: "رسالة جديدة",
    newNotification: "إشعار جديد",
};

export default AR;
